#!/bin/bash
# Change wallpaper using swaybg.

if [[ -n "${COMP_LINE}" && "${1}" == "${3}" ]]; then
  compgen -f -- "${2}"
  exit 0
fi

declare program_name
program_name="$(basename "${0}")"

if [[ "$#" -ne 1 ]]; then
  echo 1>&2 "${program_name}: error: please select a wallpaper. Try ${program_name} --help"
  exit 1
fi

case "${1}" in
  -h | --help)
    echo "usage: ${program_name} [-h | --help] <path/to/wallpaper>"
    ;;
  *)
    if ! [[ -f "${1}" ]]; then
      echo 1>&2 "${program_name}: error: please select a wallpaper. Try ${program_name} --help"
      exit 1
    fi
    declare bg_path config_dir
    config_dir="${HOME}"/.config
    bg_path="$(realpath -s --relative-to="${config_dir}" "${1}")"
    ln -fs "${bg_path}" "${config_dir}"/swaybg_wallpaper
    pkill --euid "${USER}" --exact swaybg
    swaybg -i "${config_dir}"/swaybg_wallpaper &>/dev/null & disown
    exit 0
    ;;
esac
